name: "CI"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - release-snapshot
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v3
    - name: Run nix check
      run: nix --extra-experimental-features "nix-command flakes" flake check
    - name: Install eldev dependencies
      run: git clone "https://github.com/xFA25E/abbrev-hook" && echo "(eldev-use-local-dependency \"$(pwd)/abbrev-hook\")" >Eldev-local
    - name: Run tests
      run: nix --extra-experimental-features "nix-command flakes" develop -c eldev --unstable -p -d -t -T test
